[build]
builder = "NIXPACKS"
buildCommand = "pnpm -w install --frozen-lockfile && pnpm -w --filter @sga-time-tracking/members-hub... build"

[deploy]
startCommand = "pnpm -w --filter @sga-time-tracking/members-hub... start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { 
  NODE_ENV = "production",
  NEXT_PUBLIC_API_URL = "https://api-production-ac16.up.railway.app/api"
}
