# Generated by Django 5.2.3

from django.db import migrations


def create_initial_data(apps, schema_editor):
    """
    This migration was originally used for development seed data.
    For production deployments, use the management command:
    python manage.py create_admin_user
    """
    # No-op for production - data seeding moved to management commands
    pass


def reverse_initial_data(apps, schema_editor):
    """
    Reverse function for the migration.
    Since we no longer seed data in migrations, this is a no-op.
    """
    # No-op for production - data seeding moved to management commands
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data, reverse_initial_data),
    ]
