[build]
builder = "NIXPACKS"
buildCommand = "corepack enable && pnpm install --frozen-lockfile && pnpm --filter @sga-time-tracking/clock-kiosk... build"

[deploy]
startCommand = "pnpm --filter @sga-time-tracking/clock-kiosk... start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { 
  NODE_ENV = "production",
  NEXT_PUBLIC_API_BASE_URL = "https://api-production-ac16.up.railway.app/api"
}
