[build]
builder = "NIXPACKS"

[deploy]
preDeployCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && python manage.py create_admin_user"
startCommand = "mkdir -p /app/staticfiles && python manage.py collectstatic --noinput && gunicorn time_tracking_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 300 --keep-alive 2 --log-level info --access-logfile -"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { 
  DJANGO_ENV = "production",
  CLOCK_KIOSK_URL = "https://clock-kiosk-production.up.railway.app",
  MEMBERS_HUB_URL = "https://members-hub-production.up.railway.app",
  CORS_ALLOWED_ORIGINS = "https://clock-kiosk-production.up.railway.app,https://members-hub-production.up.railway.app"
}
