[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements/production.txt"

[deploy]
startCommand = "python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:$PORT --timeout 300 --keep-alive 2 --log-level info time_tracking_backend.wsgi:application"
healthcheckPath = "/health/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { DJANGO_ENV = "production"}
